language: node_js
node_js:
- 10.15.3

# services:
#   - docker

# env:
#   - DOCKER_COMPOSE_VERSION=2

# before_install:
#   - sudo rm /usr/local/bin/docker-compose
#   - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#   - chmod +x docker-compose
#   - sudo mv docker-compose /usr/local/bin
#   - sudo docker-compose build
#   - sudo docker-compose up -d

script:
- npm test --watch=false
env:
  matrix:
  - secure: L8ffxYM9mQCQODQYwKCx8mUHibAleZqR6t6JfMHwxn/QkAbRM5l7od+StoADguE51PPbiuIUPvs0Md4EJ71aWAnt176sVIeodOSd4uvdEPH5o/2wSjb6SVAyrQfTaadv/QJxMMeElSgeDsIXSraIMPuiBA+eyIpMfewmF2l+7EtEn2/tH7jRzc44XBhB1lKcKtHAKKz+r7IQU6Koav/1zVFNmm/PywJL/xf5k0fGLgGj1VFe4C5PHG4etAm8sWS/BnY16JqmD9t6CH1ieUTZYnLcpw4e7nYHUTavY/8CVIY5mDjN7GH2Koki3HPCIhpD97vFSaCeGHHEYVeqhdu20UpJIam7pwSPW4MSQtf5LpWqqhC91aKOT3iixVN5KImbG0tRYN0ynYtuTWYpU0HxdMIVL6p5x+bfE/h7ZtFt6dUkxQLGxnIBGcN2fS2YDNVphKVHg7TOp0UEDI7B4Vm6PfRkOgvIXVOZjIan7j4O0mcR9H+XnuOTCiOUDfygxCueiqWrGKqldcQ6hfGj+QMji1+oMFwvmF/SKOt8jQORuge7dQNrI6xnOqM5UoNgKX35YzRzkrQ7ylFRDdbbr0lU05gRZKMk4V1sQXoaFgct951TRvSefxpOWBw5O+vy6BM4L+2m3vcaOw8WPE8O20BW2icmh7f5bmuTOKzzTWVPOqA=
  - secure: LBAvu5xCq3++JMvDV2kSK9i5VKfZpQYfLRkweAyfxgvQpuTJqfj9IY+mbSSB6L97wCauZOYhnBuNt3Ry+s/oaI9uLYKynKe7VrRLts+g+QiFGPmIOELVfFJfk8/DMDKic5ezkNrVB0odWkLgK3pJn4FZuXGRCei8H2qCC4jz7APH159k5atepvyRZ+1uE851Xh5GBCTN9NHLQlONTnXcYb4awKCANSGiUMBzn8DO5NiMs1NZsstjtSNjdV1IC14o8NYcNxQs8qoP+ayTy39ucRKbJs/lkd07g9Gi+1qqLfqAqt1VMQgRvld/2lhPjSoTcNmsUSSbIXUZ7xoblm+GcylerS0NnaG+eYXfZPRMpojwOt/vivuU/Q/ZgESsdqxvk/RN+thIprJgyV4uLNNfPDSAsnNslP/mcBLG6YUgClGQe3U9YX2v+7cpdMmj0q5AqtJqjXh9k7OWlsR957U5PfMcv8khPdYeF5XP0G1mVSFwlUOwNmi0VppCJ6LhSJwZ64/5P/ivkavq1EG7L2b45522Cxed9q9UJ+IK668y1/YknscGfGJb+GtLA23rIw9WH+bkfTzEIus14r9/LrVOgMxbL7lhRiXaLicwYhSl22YEbZYDPzImi8VPzSEUQnsbo1xa+2t2W2FUCnbeTyCJDLJA7qAM4O2ydbkqJboo30Y=


# after_success:
#   - sudo docker login --rohitarjunagi@gmail.com $ --password $Password registry.heroku.com
#   - sudo docker tag myangularapp:latest registry.heroku.com/adam-myangularapp/web
#   - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST = "false" ]; then sudo docker push registry.heroku.com/adam-myangularapp/web; fi